{
 "PRed": [
  {
   "PR": {
    "number": 2,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python311"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 3,
    "state": "closed"
   },
   "data": {
    "bot_rerun": 1679924224.1623476,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "4.0.1.1"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 6,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "4.0.1.1"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 7,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "4.0.1.2"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 10,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "4.0.1.3"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/1334326562.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "4.0.3"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2023.04.28.23.49.10",
 "pre_pr_migrator_attempts": {
  "pypy38": 52
 },
 "pre_pr_migrator_status": {
  "pypy38": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4963361731\">bot CI job</a>): main: ['linux_64_python3.8.____73_pypyqt5: Encountered problems while solving:\\n  - package qt5-advanced-docking-system-4.0.1-hbf79ee2_1 requires qt-main >=5.15.8,<5.16.0a0, but none of the providers can be installed\\n', 'linux_64_python3.8.____73_pypyqt6: Encountered problems while solving:\\n  - package pyside6-6.4.0-py38hf32a759_1 requires python_abi 3.8.* *_cp38, but none of the providers can be installed\\n', 'linux_64_python3.9.____73_pypyqt5: Encountered problems while solving:\\n  - package qt5-advanced-docking-system-4.0.1-hbf79ee2_1 requires qt-main >=5.15.8,<5.16.0a0, but none of the providers can be installed\\n', 'linux_64_python3.9.____73_pypyqt6: Encountered problems while solving:\\n  - package pyside6-6.4.0-py39ha53a79b_0 requires python_abi 3.9.* *_cp39, but none of the providers can be installed\\n', 'osx_64_python3.8.____73_pypyqt5: Encountered problems while solving:\\n  - package pyside2-5.13.2-py36h98d2e28_2 requires qt >=5.12.9,<5.13.0a0, but none of the providers can be installed\\n', 'osx_64_python3.8.____73_pypyqt6: Encountered problems while solving:\\n  - package pyside6-6.4.0-py38hc3b007c_0 requires libclang >=13.0.1,<14.0a0, but none of the providers can be installed\\n', 'osx_64_python3.9.____73_pypyqt5: Encountered problems while solving:\\n  - package pyside2-5.13.2-py39h717a4ca_3 requires qt >=5.12.9,<5.13.0a0, but none of the providers can be installed\\n', 'osx_64_python3.9.____73_pypyqt6: Encountered problems while solving:\\n  - package pyside6-6.4.1-py39hb1ad2af_2 requires python_abi 3.9.* *_cp39, but none of the providers can be installed\\n', 'win_64_python3.8.____73_pypyqt5: Encountered problems while solving:\\n  - package qt5-advanced-docking-system-4.0.1-h8562eab_1 requires qt-main >=5.15.8,<5.16.0a0, but none of the providers can be installed\\n', 'win_64_python3.8.____73_pypyqt6: Encountered problems while solving:\\n  - package pyside6-6.4.1-py38h1505dde_0 requires python_abi 3.8.* *_cp38, but none of the providers can be installed\\n', 'win_64_python3.9.____73_pypyqt5: Encountered problems while solving:\\n  - package qt5-advanced-docking-system-4.0.1-h8562eab_1 requires qt-main >=5.15.8,<5.16.0a0, but none of the providers can be installed\\n', 'win_64_python3.9.____73_pypyqt6: Encountered problems while solving:\\n  - package pyside6-6.4.1-py39hd5b1ee8_0 requires python_abi 3.9.* *_cp39, but none of the providers can be installed\\n']"
 },
 "smithy_version": "3.23.1"
}