{
 "bad": {
  "exception": "Command 'git diff --name-only 59535814b3c8cbd6e67b4b91bdd4889ea128964b...HEAD' returned non-zero exit status 128.",
  "traceback": [
   "Traceback (most recent call last):",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator",
   "    migrator_uid, pr_json = run(",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 313, in run",
   "    gdiff = eval_cmd(f\"git diff --name-only {head_ref.strip()}...HEAD\")",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 341, in eval_cmd",
   "    c.check_returncode()",
   "  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/subprocess.py\", line 460, in check_returncode",
   "    raise CalledProcessError(self.returncode, self.args, self.stdout,",
   "subprocess.CalledProcessError: Command 'git diff --name-only 59535814b3c8cbd6e67b4b91bdd4889ea128964b...HEAD' returned non-zero exit status 128.",
   ""
  ]
 },
 "pre_pr_migrator_attempts": {
  "version": 1
 },
 "pre_pr_migrator_status": {
  "version": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4682323619\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 313, in run\n    gdiff = eval_cmd(f\"git diff --name-only {head_ref.strip()}...HEAD\")\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 341, in eval_cmd\n    c.check_returncode()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/subprocess.py\", line 460, in check_returncode\n    raise CalledProcessError(self.returncode, self.args, self.stdout,\nsubprocess.CalledProcessError: Command 'git diff --name-only 59535814b3c8cbd6e67b4b91bdd4889ea128964b...HEAD' returned non-zero exit status 128.\n"
 }
}