{
 "PRed": [
  {
   "PR": {
    "__lazy_json__": "pr_json/240023269.json"
   },
   "data": {
    "bot_rerun": 1597087686.865649,
    "migrator_name": "CompilerRebuild",
    "migrator_version": 1,
    "name": "Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 12,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Rebuild",
    "migrator_version": 0,
    "name": "boost-1.70.0"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 13,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python38"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 14,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 2,
    "migrator_version": 0,
    "name": "boost172"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/413866039.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/485596380.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "boost_cpp1740"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/519100933.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 2,
    "migrator_version": 0,
    "name": "python39"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/575552863.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy37"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/801540996.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python310"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2021.12.13.11.03.33",
 "pre_pr_migrator_attempts": {
  "boost1780": 209,
  "pypy37": 1,
  "pypy38": 175,
  "python311": 455,
  "python39": 1
 },
 "pre_pr_migrator_status": {
  "boost1780": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3337809201\">bot CI job</a>): main: ['linux_64_python3.10.____cpython: Encountered problems while solving:\\n  - package py-boost-1.65.1-py27h3b928e7_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'linux_64_python3.8.____cpython: Encountered problems while solving:\\n  - package py-boost-1.65.1-py27h3b928e7_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'linux_64_python3.9.____cpython: Encountered problems while solving:\\n  - package py-boost-1.65.1-py27h3b928e7_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested toolchain\\n  - package py-boost-1.65.1-py27h75ca4b9_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested toolchain\\n  - package py-boost-1.65.1-py27h75ca4b9_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested toolchain\\n  - package py-boost-1.65.1-py27h75ca4b9_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'win_64_python3.10.____cpython: Encountered problems while solving:\\n  - package py-boost-1.65.1-py35_vc14h42d8cec_3 requires python >=3.5,<3.6.0a0, but none of the providers can be installed\\n', 'win_64_python3.8.____cpython: Encountered problems while solving:\\n  - package py-boost-1.65.1-py35_vc14h42d8cec_3 requires python >=3.5,<3.6.0a0, but none of the providers can be installed\\n', 'win_64_python3.9.____cpython: Encountered problems while solving:\\n  - package py-boost-1.65.1-py35_vc14h42d8cec_3 requires python >=3.5,<3.6.0a0, but none of the providers can be installed\\n']",
  "pypy37": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/577337625\">bot CI job</a>): master: ['linux_64_python3.7.____73_pypy: Encountered problems while solving.\\nProblem: package boost-1.65.1-py27_4 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'linux_64_python3.7.____cpython: Encountered problems while solving.\\nProblem: package py-boost-1.65.1-py27h3b928e7_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'linux_64_python3.8.____cpython: Encountered problems while solving.\\nProblem: package py-boost-1.65.1-py27h3b928e7_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'osx_64_python3.6.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested toolchain\\n', 'osx_64_python3.7.____73_pypy: Encountered problems while solving.\\nProblem: nothing provides requested toolchain\\nProblem: package boost-1.65.1-py27_4 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'osx_64_python3.7.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested toolchain\\nProblem: package py-boost-1.65.1-py27h75ca4b9_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested toolchain\\nProblem: package py-boost-1.65.1-py27h75ca4b9_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'win_64_python3.7.____cpython: Encountered problems while solving.\\nProblem: package py-boost-1.65.1-py27_vc9hd6400c3_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'win_64_python3.8.____cpython: Encountered problems while solving.\\nProblem: package py-boost-1.65.1-py27_vc9hd6400c3_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n']",
  "pypy38": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4950383552\">bot CI job</a>): main: ['linux_64_python3.10.____cpython: Encountered problems while solving:\\n  - package py-boost-1.65.1-py27h3b928e7_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'linux_64_python3.8.____73_pypy: Encountered problems while solving:\\n  - package py-boost-1.65.1-py27h3b928e7_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'linux_64_python3.8.____cpython: Encountered problems while solving:\\n  - package py-boost-1.65.1-py27h3b928e7_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'linux_64_python3.9.____73_pypy: Encountered problems while solving:\\n  - package py-boost-1.65.1-py27h3b928e7_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'linux_64_python3.9.____cpython: Encountered problems while solving:\\n  - package py-boost-1.65.1-py27h3b928e7_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides requested toolchain\\n  - package py-boost-1.65.1-py27h75ca4b9_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'osx_64_python3.8.____73_pypy: Encountered problems while solving:\\n  - nothing provides requested toolchain\\n  - package py-boost-1.65.1-py27h75ca4b9_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested toolchain\\n  - package py-boost-1.65.1-py27h75ca4b9_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'osx_64_python3.9.____73_pypy: Encountered problems while solving:\\n  - nothing provides requested toolchain\\n  - package py-boost-1.65.1-py27h75ca4b9_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested toolchain\\n  - package py-boost-1.65.1-py27h75ca4b9_3 requires python >=2.7,<2.8.0a0, but none of the providers can be installed\\n', 'win_64_python3.10.____cpython: Encountered problems while solving:\\n  - package py-boost-1.65.1-py35_vc14h42d8cec_3 requires python >=3.5,<3.6.0a0, but none of the providers can be installed\\n', 'win_64_python3.8.____73_pypy: Encountered problems while solving:\\n  - package py-boost-1.65.1-py35_vc14h42d8cec_3 requires python >=3.5,<3.6.0a0, but none of the providers can be installed\\n', 'win_64_python3.8.____cpython: Encountered problems while solving:\\n  - package py-boost-1.65.1-py35_vc14h42d8cec_3 requires python >=3.5,<3.6.0a0, but none of the providers can be installed\\n', 'win_64_python3.9.____73_pypy: Encountered problems while solving:\\n  - package py-boost-1.65.1-py35_vc14h42d8cec_3 requires python >=3.5,<3.6.0a0, but none of the providers can be installed\\n', 'win_64_python3.9.____cpython: Encountered problems while solving:\\n  - package py-boost-1.65.1-py35_vc14h42d8cec_3 requires python >=3.5,<3.6.0a0, but none of the providers can be installed\\n']",
  "python311": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4948340949\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1184, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 215, in run\n    feedstock_dir, repo = get_repo(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 306, in get_repo\n    _sync_default_branches(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 328, in _sync_default_branches\n    default_branch = gh.get_repo(f\"conda-forge/{reponame}\").default_branch\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/github/MainClass.py\", line 321, in get_repo\n    headers, data = self.__requester.requestJsonAndCheck(\"GET\", url)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/github/Requester.py\", line 400, in requestJsonAndCheck\n    return self.__check(\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/github/Requester.py\", line 425, in __check\n    raise self.__createException(status, responseHeaders, output)\ngithub.GithubException.GithubException: 500 null\n",
  "python39": "not solvable: master: ['linux_64_python3.7.____cpython: Encountered problems while solving.\\nProblem: package boost-1.65.1-py27_0 requires python 2.7*, but none of the providers can be installed\\n', 'linux_64_python3.8.____cpython: Encountered problems while solving.\\nProblem: package boost-1.65.1-py27_0 requires python 2.7*, but none of the providers can be installed\\n', 'linux_64_python3.9.____cpython: Encountered problems while solving.\\nProblem: package boost-1.65.1-py27_0 requires python 2.7*, but none of the providers can be installed\\n', 'osx_64_python3.6.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested toolchain\\n', 'osx_64_python3.7.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested toolchain\\nProblem: package boost-1.65.1-py27_0 requires python 2.7*, but none of the providers can be installed\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested toolchain\\nProblem: package boost-1.65.1-py27_0 requires python 2.7*, but none of the providers can be installed\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested toolchain\\nProblem: package boost-1.65.1-py27_0 requires python 2.7*, but none of the providers can be installed\\n', 'win_64_python3.7.____cpython: Encountered problems while solving.\\nProblem: package boost-1.65.1-py27_vc9_0 requires python 2.7*, but none of the providers can be installed\\n', 'win_64_python3.8.____cpython: Encountered problems while solving.\\nProblem: package boost-1.65.1-py27_vc9_0 requires python 2.7*, but none of the providers can be installed\\n', 'win_64_python3.9.____cpython: Encountered problems while solving.\\nProblem: package boost-1.65.1-py27_vc9_0 requires python 2.7*, but none of the providers can be installed\\n']"
 },
 "smithy_version": "3.15.1"
}