{
 "bad": false,
 "new_version": "0.0.201",
 "new_version_attempts": {
  "0.0.137": 2,
  "0.0.138": 2,
  "0.0.139": 3,
  "0.0.140": 1,
  "0.0.141": 1,
  "0.0.142": 1,
  "0.0.143": 1,
  "0.0.144": 1,
  "0.0.145": 1,
  "0.0.146": 1,
  "0.0.147": 1,
  "0.0.148": 1,
  "0.0.149": 1,
  "0.0.150": 1,
  "0.0.151": 1,
  "0.0.152": 1,
  "0.0.153": 1,
  "0.0.154": 1,
  "0.0.155": 1,
  "0.0.156": 1,
  "0.0.157": 1,
  "0.0.158": 1,
  "0.0.159": 1,
  "0.0.160": 1,
  "0.0.161": 1,
  "0.0.162": 1,
  "0.0.163": 1,
  "0.0.164": 1,
  "0.0.165": 1,
  "0.0.166": 1,
  "0.0.167": 1,
  "0.0.168": 1,
  "0.0.169": 1,
  "0.0.170": 1,
  "0.0.171": 1,
  "0.0.172": 1,
  "0.0.173": 1,
  "0.0.174": 1,
  "0.0.175": 1,
  "0.0.176": 1,
  "0.0.177": 1,
  "0.0.178": 1,
  "0.0.179": 1,
  "0.0.180": 1,
  "0.0.181": 1,
  "0.0.182": 1,
  "0.0.183": 1,
  "0.0.184": 1,
  "0.0.186": 1,
  "0.0.187": 1,
  "0.0.188": 1,
  "0.0.189": 1,
  "0.0.190": 1,
  "0.0.191": 1,
  "0.0.192": 1,
  "0.0.194": 1,
  "0.0.195": 1
 },
 "new_version_errors": {
  "0.0.159": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '0.0.159' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain-{{ version }}.tar.gz'\n"
 }
}