{
  "done": [
    "paraview",
    "vtk",
    "visan",
    "libspatialite",
    "pyproj",
    "geotiff",
    "gdal",
    "qgis",
    "pygplates",
    "postgis",
    "mapserver"
  ],
  "in-pr": [
    "r-proj4",
    "magics-metview-batch",
    "magics-metview",
    "fimex",
    "magics",
    "rasterio"
  ],
  "awaiting-pr": [],
  "not-solvable": [
    "r-terra",
    "r-sf",
    "pynio"
  ],
  "awaiting-parents": [
    "r-gribr",
    "cdo",
    "r-lwgeom"
  ],
  "bot-error": [
    "r-rgdal",
    "r-gdalcubes",
    "ncl"
  ],
  "_feedstock_status": {
    "cdo": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "gdal": {
      "num_descendants": 12,
      "immediate_children": [
        "mapserver",
        "ncl",
        "postgis",
        "pygplates",
        "pynio",
        "qgis",
        "r-gdalcubes",
        "r-rgdal",
        "r-sf",
        "r-terra",
        "rasterio"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/gdal-feedstock/pull/744",
      "pr_status": "unknown"
    },
    "geotiff": {
      "num_descendants": 13,
      "immediate_children": [
        "gdal",
        "qgis"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/geotiff-feedstock/pull/54",
      "pr_status": "unknown"
    },
    "libspatialite": {
      "num_descendants": 13,
      "immediate_children": [
        "gdal",
        "qgis"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/libspatialite-feedstock/pull/93",
      "pr_status": "unknown"
    },
    "magics": {
      "num_descendants": 1,
      "immediate_children": [
        "cdo"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/magics-feedstock/pull/121",
      "pr_status": "unstable"
    },
    "ncl": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4873132896\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 282, in run\n    eval_cmd(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 341, in eval_cmd\n    c.check_returncode()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/subprocess.py\", line 460, in check_returncode\n    raise CalledProcessError(self.returncode, self.args, self.stdout,\nsubprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.\n"
    },
    "paraview": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/paraview-feedstock/pull/181",
      "pr_status": "unknown"
    },
    "postgis": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/postgis-feedstock/pull/93",
      "pr_status": "unknown"
    },
    "pynio": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4874006413\">bot CI job</a>): main: ['linux_64_numpy1.21python3.10.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0e7c1b1_3 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'linux_64_numpy1.21python3.8.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0e7c1b1_3 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'linux_64_numpy1.21python3.9.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0e7c1b1_3 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'linux_64_numpy1.23python3.11.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0e7c1b1_3 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'osx_64_numpy1.21python3.10.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h32fa94e_6 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'osx_64_numpy1.21python3.8.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h32fa94e_6 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'osx_64_numpy1.21python3.9.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h32fa94e_6 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'osx_64_numpy1.23python3.11.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h32fa94e_6 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n']"
    },
    "pyproj": {
      "num_descendants": 1,
      "immediate_children": [
        "qgis"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/pyproj-feedstock/pull/135",
      "pr_status": "unknown"
    },
    "qgis": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/qgis-feedstock/pull/319",
      "pr_status": "unknown"
    },
    "r-proj4": {
      "num_descendants": 1,
      "immediate_children": [
        "r-gribr"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/r-proj4-feedstock/pull/40",
      "pr_status": "unstable"
    },
    "r-rgdal": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4873132896\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 282, in run\n    eval_cmd(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 341, in eval_cmd\n    c.check_returncode()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/subprocess.py\", line 460, in check_returncode\n    raise CalledProcessError(self.returncode, self.args, self.stdout,\nsubprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.\n"
    },
    "r-sf": {
      "num_descendants": 1,
      "immediate_children": [
        "r-lwgeom"
      ],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4874006413\">bot CI job</a>): main: ['linux_64_r_base4.1: Encountered problems while solving:\\n  - package r-base-4.1.0-h9e01966_0 requires pcre2 >=10.36,<10.37.0a0, but none of the providers can be installed\\n', 'linux_aarch64_r_base4.1: Encountered problems while solving:\\n  - package r-base-4.1.0-hfd28f70_0 requires pcre2 >=10.36,<10.37.0a0, but none of the providers can be installed\\n', 'linux_ppc64le_r_base4.1: Encountered problems while solving:\\n  - package r-base-4.1.0-h0f82cec_0 requires pcre2 >=10.36,<10.37.0a0, but none of the providers can be installed\\n', 'osx_64_r_base4.1: Encountered problems while solving:\\n  - package r-base-4.1.0-h4d23a9d_0 requires pcre2 >=10.36,<10.37.0a0, but none of the providers can be installed\\n']"
    },
    "rasterio": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/rasterio-feedstock/pull/264",
      "pr_status": "unstable"
    },
    "vtk": {
      "num_descendants": 1,
      "immediate_children": [
        "visan"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/vtk-feedstock/pull/293",
      "pr_status": "unknown"
    },
    "r-gribr": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "r-lwgeom": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "magics-metview": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/magics-metview-feedstock/pull/64",
      "pr_status": "unstable"
    },
    "magics-metview-batch": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/magics-metview-batch-feedstock/pull/55",
      "pr_status": "unstable"
    },
    "fimex": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/fimex-feedstock/pull/55",
      "pr_status": "unstable"
    },
    "r-gdalcubes": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4873132896\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 282, in run\n    eval_cmd(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 341, in eval_cmd\n    c.check_returncode()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/subprocess.py\", line 460, in check_returncode\n    raise CalledProcessError(self.returncode, self.args, self.stdout,\nsubprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.\n"
    },
    "r-terra": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4874006413\">bot CI job</a>): main: ['linux_64_r_base4.1: Encountered problems while solving:\\n  - package libgdal-3.6.0-h2d85cf6_2 requires proj >=9.1.0,<9.1.1.0a0, but none of the providers can be installed\\n', 'linux_64_r_base4.2: Encountered problems while solving:\\n  - package libgdal-3.6.0-h2d85cf6_2 requires proj >=9.1.0,<9.1.1.0a0, but none of the providers can be installed\\n', 'linux_aarch64_r_base4.1: Encountered problems while solving:\\n  - package libgdal-3.6.0-h39dad11_2 requires proj >=9.1.0,<9.1.1.0a0, but none of the providers can be installed\\n', 'linux_aarch64_r_base4.2: Encountered problems while solving:\\n  - package libgdal-3.6.0-h39dad11_2 requires proj >=9.1.0,<9.1.1.0a0, but none of the providers can be installed\\n', 'linux_ppc64le_r_base4.1: Encountered problems while solving:\\n  - package libgdal-3.6.0-h24b9062_2 requires proj >=9.1.0,<9.1.1.0a0, but none of the providers can be installed\\n', 'linux_ppc64le_r_base4.2: Encountered problems while solving:\\n  - package libgdal-3.6.0-h24b9062_2 requires proj >=9.1.0,<9.1.1.0a0, but none of the providers can be installed\\n', 'osx_64_r_base4.1: Encountered problems while solving:\\n  - package libgdal-3.6.0-h12400bf_2 requires proj >=9.1.0,<9.1.1.0a0, but none of the providers can be installed\\n', 'osx_64_r_base4.2: Encountered problems while solving:\\n  - package libgdal-3.6.0-h12400bf_2 requires proj >=9.1.0,<9.1.1.0a0, but none of the providers can be installed\\n']"
    },
    "visan": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/visan-feedstock/pull/15",
      "pr_status": "unknown"
    },
    "mapserver": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/mapserver-feedstock/pull/25",
      "pr_status": "unknown"
    },
    "pygplates": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/pygplates-feedstock/pull/5",
      "pr_status": "unknown"
    }
  }
}